### ISSUE TITLE
[emacs 28.0.90] Issue with nano-subtle or nano-faded when text highlighted in macOS

### ISSUE THREAD

**Issue by maikol-solis** [rougier/nano-theme#17]
Hi! 

I installed this build (https://github.com/jimeh/emacs-builds/releases/tag/Emacs.2021-12-05.e3427fa.emacs-28) of emacs 28.0.90 (pretest) 

When I highlight some text with` nano-subtle` or `nano-faded` faces, the foreground text become completely black. 

This is how it looks, the `#+STARTUP` line in some org file:

![image](https://user-images.githubusercontent.com/4078489/144863380-3a115511-2832-422d-b470-263715f6abd0.png)

I'm using doom-emacs with this simple configuration 

```
(use-package! nano-theme
  :config
  (nano-dark))
```

I guess that the foreground and background should be inverted to keep the contrast. 

PS: In emacs 27.2 I haven't had this behavior. Everything looked fine. 

Best.

**Comment by maikol-solis** [comment]
I found the solution. 

It's just to add this line in a `custom-set-faces`

```
 '(region ((t :distant-foreground nil)))
```

Thanks.

**Comment by rougier** [comment]
Thanks for the report and the fix. Can you make a PR?

**Comment by maikol-solis** [comment]
I did it. Please let me know if I put the fix in the right place. 

Thanks.
