### ISSUE TITLE
`Error` (`nano-critical`) face has some display issues

### ISSUE THREAD

**Issue by maikol-solis** [rougier/nano-theme#20]
Hi! 

I'm using nano-theme (nano-dark) with doom-emacs and I found a glitch in org-mode/org-agenda. 

When I use priority `[#A]` in a heading, the foreground of the letter or icon should be yellow with dark background. 

However, if I put the cursor above the heading, the foreground turns black with the same dark background. 

This is the behavior in org-mode

https://user-images.githubusercontent.com/4078489/150639911-c6f06440-fd8d-41cf-98e0-3d30a625d99f.mov

in org-agenda

https://user-images.githubusercontent.com/4078489/150640168-8a1439f4-d6a3-4ae8-a71a-086bb386f3f0.mov

The face that I found related to this is `error` (https://github.com/rougier/nano-theme/blob/master/nano-theme.el#L695), inherited by `nano-critical`(https://github.com/rougier/nano-theme/blob/master/nano-theme.el#L630). 

For the moment I couldn't find how to fix this. 

I hope you can give some lights about it. 

Thanks.

**Comment by rougier** [comment]
I've just changed the `nano-critical` face to be a bit less agressive. It is now bold and red (but no bakground). Hopefully it'll solve your problem.

**Comment by maikol-solis** [comment]
It works perfectly. Thanks!
![image](https://user-images.githubusercontent.com/4078489/151908254-55742793-ca0f-45d2-92a0-32d726ddf5e0.png)
