### ISSUE TITLE
`line-number-current-line` displays different than `line-number` 

### ISSUE THREAD

**Issue by maikol-solis** [rougier/nano-theme#21]
In doom-emacs if you use the Zen mode (https://github.com/hlissner/doom-emacs/tree/master/modules/ui/zen), you get an annoying behavior with `line-number-current-line` because is bigger than `line-number`.  The problem is related when you increase the font of all buffer. 

This causes that every time you move in the buffer, the current line moves slightly to the right.  Here there is a screenshot:

![image](https://user-images.githubusercontent.com/4078489/151577125-08741b5b-6c41-45ac-b146-5b5d3983c946.png)

Best.

**Comment by maikol-solis** [comment]
I solve it with this 

```
'(line-number-current-line :inherit nil))
```

**Comment by rougier** [comment]
Thanks for the report and the fix. Can you make  a PR (or can do the fix)?
