### ISSUE TITLE
nano-mode does not find roboto mono 

### ISSUE THREAD

**Issue by albreche** [rougier/nano-theme#22]
Hi, 
  nano-mode, and more precisely find-font does not find robot mono. 
The font exists on my PC, running Windows 10. 
Note that font-info find the font-spec (font-spec :name "RobotoMono Nerd Font Mono")

**Comment by albreche** [comment]
my bad

**Comment by rougier** [comment]
You fixed the problem?

**Comment by albreche** [comment]
Yes, it was a misconfiguration of my own. Envoyé de mon Galaxy A52s 5G Orange
-------- Message d'origine --------De : "Nicolas P. Rougier" ***@***.***> Date : 31/01/2022  18:58  (GMT+01:00) À : rougier/nano-theme ***@***.***> Cc : albreche ***@***.***>, State change ***@***.***> Objet : Re: [rougier/nano-theme] nano-mode does not find roboto mono  (Issue #22) 
You fixed the problem?
