### ISSUE TITLE
Boldness isn't working properly

### ISSUE THREAD

**Issue by librarianmage** [rougier/nano-theme#24]
Hello,

I'm finding that `nano-strong` doesn't actually make text bolder than normal

Current config:
![image](https://user-images.githubusercontent.com/12386291/162626108-72f961b9-ee1c-4d53-899d-2a7f1f0d6af1.png)

**Comment by rougier** [comment]
The default weight is "light" while the "bold" is "regular". You need a font that support the light weight. Else, you can set the weight of nano-default face to regular and the one of nano-strong to bold.

**Comment by librarianmage** [comment]
I am using the default font, since I commented out my font definitions to
confirm.

**Comment by librarianmage** [comment]
I'm not sure what caused this but it stopped happening
