### ISSUE TITLE
magit-mode-line-process and magit-mode-line-process-error are invisible in nano-light

### ISSUE THREAD

**Issue by luispauloml** [rougier/nano-theme#27]
In the light version, `magit-mode-line-process` and `magit-mode-line-process-error` are invisible in the active window and inconsistent in other windows:

![magit-process-mode-line](https://user-images.githubusercontent.com/30757952/164986449-01043a57-e371-4ea2-8b29-8b5cd8ce0324.png)

A simple way to reproduce this:
1. Access any directory that is git repository.
2. `M-x nano-light`.
4. `M-x magit-status`.
5. `M-x magit-process-buffer`.
6. Have the status window and the process window both visible at the same time.
5. Amend last commit (default key sequence in a Magit buffer: `c a`) and observe the mode lines while the `COMMIT_EDITMSG` buffer is loaded, it will show `magit-mode-line-process` in both windows.
7. Abort amending (default key binding in the commit message window: `C-c C-k`) and observe the mode lines, it will show `magit-mode-line-process-error`.
   
The reason for this is that both faces are set to `nano-default` (lines 1363-1364 in `nano-theme.el`):

```
    '(magit-mode-line-process                ((t (:inherit nano-default))))
    '(magit-mode-line-process-error          ((t (:inherit nano-default))))
```

Setting both to `nano-default-i` will make them visible in the active window, but inconsistent in other windows.  I set both to
`nano-critical`, but that's just me.

**Comment by rougier** [comment]
Thanks for the report and sorry for late response. magit has a lot of faces and I was not sure which one is used when. for error message , best would be to inherit from nano-error. I'll change it.

**Comment by luispauloml** [comment]
But Nano does not define any `nano-error`. From Eshell, after commit 06d7c94:

``` eshell
$ grep nano-error *
1 match for "nano-error" in buffer: nano-theme.el
   1402:    '(magit-mode-line-process-error          ((t (:inherit nano-error))))

$ grep error *
6 matches in 5 lines for "error" in buffer: nano-theme.el
    712:   '(error                         ((t (:inherit nano-critical))))
   1224:    '(elfeed-log-error-level-face            ((t (:inherit nano-popout))))
   1236:    '(deft-filter-string-error-face         ((t (:inherit nano-popout))))
   1402:    '(magit-mode-line-process-error          ((t (:inherit nano-error))))
   1433:    '(magit-signature-error                  ((t (:inherit nano-default))))
```

Perhaps you wanted to say `error`, which in turns inherits from `nano-critical`, which is the one I suggested.

**Comment by rougier** [comment]
Sorry, I meant nano-critical. I will push a fix.

**Comment by rougier** [comment]
Done.
