### ISSUE TITLE
Add toggle function

### ISSUE THREAD

**Issue by bdarcus** [rougier/nano-theme#3]
A minor thing to consider; may or may not be a good idea here:

Rather than, or in addition to, dedicated "light" and "dark" interactive functions, how about a modus-like "toggle" function?

https://github.com/protesilaos/modus-themes/blob/e98a4eaa8a4ec394c585af525612f8b181b602fc/modus-themes.el#L3514

It seems modus has the toggle function interactive, and the functions it references not.

**Comment by rougier** [comment]
Toggle function would be a good addition yes (+ a custom toggle setting) I'll try to do that (unless you want to make a PR)

**Comment by merement** [comment]
Since there are only two mutually exclusive themes, they are easy to toggle. I'm using a code like this 

    (setq-default my/light-theme-p t)
    (defun my/load-light-theme ()
               (setq my/light-theme-p t)
               (nano-light))
    (defun my/load-dark-theme ()
               (setq my/light-theme-p nil)
               (nano-dark))

    (load-theme 'nano t)
    (global-set-key [f5] (lambda ()
                       (interactive)
                       (if my/light-theme-p
                           (my/load-dark-theme)
                           (my/load-light-theme))))

**Comment by rougier** [comment]
I've just added a `nano-theme-toggle`
