### ISSUE TITLE
after install nano theme i getting issue with org tables

### ISSUE THREAD

**Issue by vijaypanchalr3** [rougier/nano-theme#30]
![Screenshot from 2022-06-09 10-05-18](https://user-images.githubusercontent.com/72692300/172765039-cb883cb2-6c75-4acf-95b9-61dfdf3d81eb.png)

**Comment by rougier** [comment]
It seems you're using a non monosize font, that could be the reason. How did you identify nano-theme as being the culprit?

**Comment by rougier** [comment]
Put the cursor on any character and type 'M-x describe-char' (to check which face is used). Once the face has been identified, type 'M-x customize-face' and enter the face you've just found. Then you can post the information here.
