### ISSUE TITLE
Some options in Magit popups are indiscernible

### ISSUE THREAD

**Issue by luispauloml** [rougier/nano-theme#43]
Some of Magit's commands allow the user to set an option, such as the one for pulling changes from a repository (accessed via <kbd>F</kbd> in Magit's home buffer) as show in this figure:

![before-customize](https://user-images.githubusercontent.com/30757952/200324797-b27c134d-ed3c-4212-a945-4d1f2b0ccbb7.png)

In this example, by pressing <kbd>r</kbd> the user can configure `branch.master.rebase` by cycling among any of three options: `true`, `false`, and `pull.rebase:false`. Magit uses a different font face to highlight which options is selected, as can be seen in the default theme. These faces are `transient-value` and `transient-inactive-value`, which belongs to the [Transient package](https://github.com/magit/transient/), the backend responsible for Magit's popups, [and which are defined as](https://github.com/magit/transient/blob/ad953cc3c5b8a066d3da11a8527c035744f1385f/lisp/transient.el#L447-L453):

```elisp
(defface transient-value '((t :inherit font-lock-string-face))
  "Face used for values."
  :group 'transient-faces)

(defface transient-inactive-argument '((t :inherit shadow))
  "Face used for inactive arguments."
  :group 'transient-faces)
```

However, Nano redefines `shadow` and `font-lock-string-face` to inherit only `nano-faded`:
https://github.com/rougier/nano-theme/blob/124ea271475556602ce293f788644a3e39b06f2f/nano-theme-support.el#L716
https://github.com/rougier/nano-theme/blob/124ea271475556602ce293f788644a3e39b06f2f/nano-theme-support.el#L771

This makes these two fonts indiscernible from each other. My solution was to customize only `transient-value`, making it inherit `default`:

```elisp
(custom-set-faces '(transient-value ((t (:inherit default)))))
```

The result is this:

![after-customize](https://user-images.githubusercontent.com/30757952/200324828-3d9f5a65-89d9-4a54-9aa9-df11d01c0757.png)

I guess that as an end user, this is fine, but I would think that setting only a single font of a whole package and ignoring all the others is not recommended for theme package, and I do not know what to suggest to fix this.

**Comment by rougier** [comment]
Thanks. I didn't even know magit was doing this highlighting because I've  never seen it... Coudl you make a PR with your changes?
