### ISSUE TITLE
Expanding theme options?

### ISSUE THREAD

**Issue by 9s-l-s9** [rougier/nano-theme#52]
Hello,

I love the general idea of Nano Emacs and would like to adapt other themes to follow a similar style. I would essentially change existing themes in a similar way as Nord-dark and Material light have been for the current themes. 

For example, I would like to include a version based on ayu dark: 

![image](https://github.com/rougier/nano-theme/assets/49971875/c0f770cb-f30e-4a59-b817-593ebeda22b3)
(Here a Obsidian version, source: https://github.com/bcdavasconcelos/Themes/tree/a8f85ce9fac2a19adb2f837df00cd07321283631/Obsidian )

Now, I know that Nano is way more opinionated than other themes and additional variations would have to follow the same style. 

Therefore for me, the question than is: Should I fork and create my own version, with the mentioned variations? Or would you be open to accept new theme variations, as long as they follow the style of Nano themes? I would imagine this "nano-theme" repo to be closer to the doom-themes package, covering multiple themes that could be selected. 

Thank you in advance :)

**Comment by rougier** [comment]
To help discovery of your theme, a dedicated package might be easier. If you want to reference nano-theme, you can named it something like (for example) nano-theme-ayu-dark. Now, if you only modify the 6 base colors, maybe sub-theme could be integrated.
