### ISSUE TITLE
Theme does not work with new frame

### ISSUE THREAD

**Issue by nauhygon** [rougier/nano-theme#6]
In the original frame, I set it to dark mode with `nano-dark`. But once I create a new frame with `make-frame`, the new frame is rendered with a lighter theme (but not exactly the nano-light theme as far as I can tell). Then if I load dark mode with `nano-dark` in the new frame, the frame goes into dark mode as intended, but the original frame strangely changes to light mode. Unsure if others see the same.

**Comment by rougier** [comment]
I get the same problem actually (I've never tried before). I think the problem was that I set the default frame background was not set. Hopefully it is fixed now.

**Comment by nauhygon** [comment]
Thanks so much for the quick fix! I can confirm that it has fixed the issue. :-)
